version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_DB: sityo
      POSTGRES_USER: manol
      POSTGRES_PASSWORD: Manol.13
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pwa:
    build: ./pwa
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgis_data:


# docker-compose up --build     # construir
# docker ps                     # verificar que existen los contenedores
# docker-compose down -v        # quitar contenedores, redes y volumenes
