FROM postgis/postgis:17-3.5-alpine
ENV POSTGRES_DB=sityo
ENV POSTGRES_USER=manol
ENV POSTGRES_PASSWORD=Manol.13
EXPOSE 5432

# docker build -t post-gis .
# docker run -d -p 5432:5432 --name sythio-gis post-gis 